#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
ENV ASPNETCORE_URLS=http://*:8080
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["EverGlow.API/nuget.config", "EverGlow.API/"]
COPY ["EverGlow.API/EverGlow.API.csproj", "EverGlow.API/"]
RUN dotnet restore "EverGlow.API/EverGlow.API.csproj"
COPY . .
WORKDIR "/src/EverGlow.API"
RUN dotnet build "EverGlow.API.csproj" -c Release -o /app/build

FROM node:19-alpine AS reactbuild
WORKDIR /app
COPY TheDoor.Dash.Web.Api/ClientApp/package.json .
COPY TheDoor.Dash.Web.Api/ClientApp/package-lock.json .
RUN npm ci --silent
COPY TheDoor.Dash.Web.Api/ClientApp/. .
RUN npm run build:sandbox

FROM build AS publish
RUN dotnet publish "TheDoor.Dash.Web.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY --from=reactbuild /app/dist /app/wwwroot
ENTRYPOINT ["dotnet", "TheDoor.Dash.Web.Api.dll"]